# Generated by Django 5.2.2 on 2025-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestras', models.IntegerField()),
                ('error_estimacion', models.FloatField()),
                ('nivel_confianza', models.FloatField()),
            ],
        ),
    ]
