# Generated by Django 5.2.2 on 2025-06-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_errores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoErrores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_real', models.FloatField()),
                ('valor_aprox', models.FloatField()),
                ('error_abs', models.FloatField()),
                ('error_rel', models.FloatField()),
                ('error_porc', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo de Errores',
                'verbose_name_plural': 'Cálculos de Errores',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.DeleteModel(
            name='Estimacion',
        ),
    ]
